In [ ]:
import pandas as pd

In [ ]:
from datasets import load_dataset

In [ ]:
dataset = load_dataset("lukebarousse/data_jobs")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

data_jobs.csv:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [ ]:
df = dataset['train'].to_pandas()

In [ ]:
#data cleanup
df['jo_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [ ]:
df['job_country']

0         United States
1                Mexico
2               Germany
3         United States
4                 Sudan
              ...
785736        Singapore
785737          Germany
785738         Malaysia
785739            Sudan
785740            India
Name: job_country, Length: 785741, dtype: object

In [ ]:
df['job_country'].value_counts()

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
                   ...
Guinea                 4
Lesotho                3
Mauritania             3
Bhutan                 3
Maldives               2
Name: count, Length: 160, dtype: int64

In [ ]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,jo_posted_date
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None,2023-06-16 13:44:15
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr...",2023-01-14 13:18:07
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",2023-10-10 13:14:55
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',...",2023-07-04 13:01:41
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl...",2023-08-07 14:29:36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete...",2023-03-13 06:16:16
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi...",2023-03-12 06:18:18
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}",2023-03-12 06:32:36
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh...",2023-03-12 06:32:15
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}",2023-03-13 06:16:31

In [ ]:
df['job_country'].value_counts().head(20)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Canada             16029
Mexico             15139
Poland             14793
Portugal           14508
Australia          12955
South Africa       12414
Belgium            12078
Philippines        11786
Ireland            11162
Switzerland         9924
Name: count, dtype: int64

In [ ]:
df['job_country'].isin(['brazil'])

0         False
1         False
2         False
3         False
4         False
          ...
785736    False
785737    False
785738    False
785739    False
785740    False
Name: job_country, Length: 785741, dtype: bool

In [ ]:
df['job_country'].isin(['brazil']).any()

np.False_

In [ ]:
us_jobs = df[df['job_country'] == "United States"]

In [ ]:
us_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,jo_posted_date
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None,2023-06-16 13:44:15
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',...",2023-07-04 13:01:41
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '...",2023-11-07 14:01:59
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['...",2023-03-27 13:18:18
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'...",2023-04-23 13:02:57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,None,NaN,NaN,JPMorgan Chase & Co.,None,None,2023-10-16 06:01:53
785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,None,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['...",2023-07-16 06:01:27
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}",2023-04-21 06:02:31
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,None,NaN,NaN,Axelon Services Corporation,None,None,2023-01-28 06:02:55
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,None,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ...",2023-01-09 06:00:25

In [ ]:
us_jobs = us_jobs[us_jobs['salary_year_avg'].notna()]

In [ ]:
us_jobs.groupby('job_title_short').count()

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,jo_posted_date
job_title_short,,,,,,,,,,,,,,,,,
Business Analyst,431,425,431,430,431,431,431,431,431,431,431,431,0,431,355,355,431
Cloud Engineer,20,20,20,19,20,20,20,20,20,20,20,20,0,20,18,18,20
Data Analyst,4350,4285,4350,4342,4350,4350,4350,4350,4350,4350,4350,4350,0,4350,3868,3868,4350
Data Engineer,2915,2869,2915,2915,2915,2915,2915,2915,2915,2915,2915,2915,0,2915,2828,2828,2915
Data Scientist,4553,4498,4553,4550,4553,4553,4553,4553,4553,4553,4553,4553,0,4553,4025,4025,4553
Machine Learning Engineer,128,128,128,128,128,128,128,128,128,128,128,128,0,128,117,117,128
Senior Data Analyst,913,903,913,913,913,913,913,913,913,913,913,913,0,913,821,821,913
Senior Data Engineer,1058,1041,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,0,1058,1044,1044,1058
Senior Data Scientist,1241,1220,1241,1240,1241,1241,1241,1241,1241,1241,1241,1241,0,1241,1149,1149,1241
Software Engineer,157,155,157,157,157,157,157,157,157,157,157,157,0,157,133,133,157

In [ ]:
us_jobs.groupby('job_title_short')['salary_year_avg'].count()

job_title_short
Business Analyst              431
Cloud Engineer                 20
Data Analyst                 4350
Data Engineer                2915
Data Scientist               4553
Machine Learning Engineer     128
Senior Data Analyst           913
Senior Data Engineer         1058
Senior Data Scientist        1241
Software Engineer             157
Name: salary_year_avg, dtype: int64

In [ ]:
us_jobs.groupby("job_title_short")['salary_year_avg'].min()

job_title_short
Business Analyst             35000.0
Cloud Engineer               42000.0
Data Analyst                 25000.0
Data Engineer                23496.0
Data Scientist               30000.0
Machine Learning Engineer    44408.5
Senior Data Analyst          35360.0
Senior Data Engineer         45000.0
Senior Data Scientist        55000.0
Software Engineer            48982.0
Name: salary_year_avg, dtype: float64

In [ ]:
us_jobs.groupby("job_title_short")['salary_year_avg'].agg(['min', 'max', 'median', 'count'])

                               min       max    median  count
job_title_short
Business Analyst           35000.0  387460.0   90000.0    431
Cloud Engineer             42000.0  221844.0  116100.0     20
Data Analyst               25000.0  375000.0   90000.0   4350
Data Engineer              23496.0  525000.0  125000.0   2915
Data Scientist             30000.0  960000.0  130000.0   4553
Machine Learning Engineer  44408.5  315000.0  150000.0    128
Senior Data Analyst        35360.0  425000.0  110000.0    913
Senior Data Engineer       45000.0  375000.0  150000.0   1058
Senior Data Scientist      55000.0  475000.0  155000.0   1241
Software Engineer          48982.0  375000.0  130000.0    157

In [ ]:
us_jobs.groupby("job_title_short")['salary_year_avg'].agg(['min', 'max', 'median', 'count'] ).sort_values(by="median")

                               min       max    median  count
job_title_short
Business Analyst           35000.0  387460.0   90000.0    431
Data Analyst               25000.0  375000.0   90000.0   4350
Senior Data Analyst        35360.0  425000.0  110000.0    913
Cloud Engineer             42000.0  221844.0  116100.0     20
Data Engineer              23496.0  525000.0  125000.0   2915
Data Scientist             30000.0  960000.0  130000.0   4553
Software Engineer          48982.0  375000.0  130000.0    157
Machine Learning Engineer  44408.5  315000.0  150000.0    128
Senior Data Engineer       45000.0  375000.0  150000.0   1058
Senior Data Scientist      55000.0  475000.0  155000.0   1241

In [ ]:
us_jobs.groupby("job_title_short")['salary_year_avg'].agg(['min', 'max', 'median', 'count'] ).sort_values(by="median", ascending=False)

                               min       max    median  count
job_title_short
Senior Data Scientist      55000.0  475000.0  155000.0   1241
Machine Learning Engineer  44408.5  315000.0  150000.0    128
Senior Data Engineer       45000.0  375000.0  150000.0   1058
Data Scientist             30000.0  960000.0  130000.0   4553
Software Engineer          48982.0  375000.0  130000.0    157
Data Engineer              23496.0  525000.0  125000.0   2915
Cloud Engineer             42000.0  221844.0  116100.0     20
Senior Data Analyst        35360.0  425000.0  110000.0    913
Business Analyst           35000.0  387460.0   90000.0    431
Data Analyst               25000.0  375000.0   90000.0   4350